FULLSCREEN = False

MENU_CENTER_X = 0.5 #default:0.5 center horizontally
STUDIO_HEIGHT = 0.15 #default:0.15 XX% down from top
TITLE_HEIGHT = 0.25 #default:0.25 XX% down from top
MENU_START_HEIGHT = 0.5 #default:0.5 XX% down from top
MENU_SPACING = 50 #default:50 XX pixels between menu items
ASTEROID_MIN_RADIUS = 20 #how small it can be default: 20
ASTEROID_KINDS = 5 #how many differnt asteroids there can be default: 3
ASTEROID_SPAWN_RATE = 0.8  # seconds default: 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS #handles asteroids default: i wouldnt, if i were you, change the value
PLAYER_RADIUS = 20 #shh the player is also a circle default: 20
PLAYER_TURN_SPEED = 300 #turn speed >.> default: 300
PLAYER_SPEED = 202 #how fast the player goes default: 202
SHOT_RADIUS = 5 # how big the bullets are default: 5
PLAYER_SHOOT_SPEED = 505 # how fast to pew-pew default: 505
PLAYER_SHOTCD = 0.3 #in seconds default: 0.3
PLAYER_INVINCIBLITY_TIME = 1 #in seconds default: 1
ASTEROID_POINTS = 8 # number of vertices on each asteroid, default: 8